// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const get = `-- name: Get :one
SELECT name, type, delta, value, hash FROM metrics
WHERE name = $1 LIMIT 1
`

type GetRow struct {
	Name  string
	Type  string
	Delta pgtype.Int8
	Value pgtype.Float8
	Hash  pgtype.Text
}

func (q *Queries) Get(ctx context.Context, name string) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, name)
	var i GetRow
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Delta,
		&i.Value,
		&i.Hash,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT name, type, delta, value, hash FROM metrics
ORDER BY id
`

type GetAllRow struct {
	Name  string
	Type  string
	Delta pgtype.Int8
	Value pgtype.Float8
	Hash  pgtype.Text
}

func (q *Queries) GetAll(ctx context.Context) ([]GetAllRow, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Delta,
			&i.Value,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE metrics SET (delta, value, updated_at) = ($1, $2, $3)
WHERE name = $4
`

type UpdateParams struct {
	Delta     pgtype.Int8
	Value     pgtype.Float8
	UpdatedAt pgtype.Timestamptz
	Name      string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.Delta,
		arg.Value,
		arg.UpdatedAt,
		arg.Name,
	)
	return err
}

const write = `-- name: Write :exec
INSERT INTO metrics (
  name, type, delta, value, hash
) VALUES (
  $1,$2,$3,$4,$5
)
`

type WriteParams struct {
	Name  string
	Type  string
	Delta pgtype.Int8
	Value pgtype.Float8
	Hash  pgtype.Text
}

func (q *Queries) Write(ctx context.Context, arg WriteParams) error {
	_, err := q.db.Exec(ctx, write,
		arg.Name,
		arg.Type,
		arg.Delta,
		arg.Value,
		arg.Hash,
	)
	return err
}
