// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID        int64
	Name      string
	Type      string
	Delta     pgtype.Int8
	Value     pgtype.Float8
	Hash      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
